### PR TITLE
nurbs splines visialization v1

### PR DESCRIPTION
**Pull request by DmitriiTunikov**
# What's done
* Implementation of De Boor's algorithm for NURBS curves
* Splen building visualization
# Why is it done
For any one could understand - how De Boor's algorithm works
# How to test
1. Clone repo
2. Open in python IDE
3. pip install Pillow (link to drawing lib https://note.nkmk.me/en/python-pillow-basic/)
4. In main.py you can change contoll points and width/height of output gif window size. After runing main.py you will get de_boor.gif file, which is the algorithm visualization for current controll points

### CODE REVIEW

**Comment by daniilsavchuk** [comment]
Please do the following:
1. Name the PR properly
2. Provide an appropriate PR description including What Why How and How to test points
3. Invite me to review this PR as a reviewer to let me receive notifications via the e-mail
4. Provide a read.me using English

**Comment by DmitriiTunikov** [comment]
@daniilsavchuk смог тебя добавить только в assignes. Почему-то в reviewers тебя не видит github.

**Comment by daniilsavchuk** [comment]
Ok. Seems good. Could you please move your README.md contend to a PR description (that what I mention). And fulfill README.md with readme guidelines. 

Thank you!. Lab is ok and I put 1 point to table.

**Comment by DmitriiTunikov** [comment]
@daniilsavchuk 
Я случайно закрыл PR. Но думаю это не большая проблема.
Перенес readme в описание PR.
О каких гайдах идет речь? По-моему readme итак нормально вполне оформлен.

**Comment by daniilsavchuk** [comment]
@DmitriiTunikov  everything is ok :)

**Pull request merged**
